[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  HIBP_API_KEY = "9b943109e49542d59147c95d9d73a945"
  NEXT_PUBLIC_DEPLOYED_ENV = "netlify"
  SKIP_ENV_VALIDATION = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure static assets are properly served
[[headers]]
  for = "/static/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Add proper next-image handling
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

# This redirect should be removed as it interferes with Next.js's routing
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200
#  force = false