[build]
  command = "npm install && npm run build"
  publish = ".next"
  # Add clearer environment variables for debugging
  environment = { NEXT_PUBLIC_DEPLOYED_ENV = "netlify" }

[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_TELEMETRY_DISABLED = "1"
  # Add API key to environment
  HIBP_API_KEY = "9b943109e49542d59147c95d9d73a945"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure static assets are properly served
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Add proper next-image handling
[[redirects]]
  from = "/_next/image*"
  to = "/_next/image:splat"
  status = 200

# This configuration is used for standard page routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false